"""followers

Revision ID: 79989fb6fd22
Revises: a2ee1870876f
Create Date: 2021-03-24 17:44:33.790114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79989fb6fd22'
down_revision = 'a2ee1870876f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
